# Generated by Django 5.2.8 on 2026-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_bookings_unique_booking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="adults",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bookings",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="infants",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pets",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
