# Generated by Django 5.2.8 on 2025-11-24 04:47

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amineties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wifi', 'Wi-Fi'), ('tv', 'TV'), ('kitchen', 'Kitchen'), ('washer', 'Washer'), ('dryer', 'Dryer'), ('air_conditioning', 'Air Conditioning'), ('heating', 'Heating'), ('dedicated_workspace', 'Dedicated Workspace'), ('parking', 'Free Parking'), ('gym', 'Gym'), ('pool', 'Pool'), ('hot_tub', 'Hot Tub'), ('bbq_grill', 'BBQ Grill'), ('patio', 'Patio or Balcony'), ('garden', 'Garden'), ('smoke_alarm', 'Smoke Alarm'), ('first_aid_kit', 'First Aid Kit'), ('fire_extinguisher', 'Fire Extinguisher'), ('breakfast', 'Breakfast Provided'), ('pets_allowed', 'Pets Allowed'), ('long_term_stays', 'Long-Term Stays Allowed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/listings')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('hotel', 'Hotel Room'), ('shared_room', 'Shared Room'), ('guest_house', 'Guest House')], max_length=15)),
                ('max_guests', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')])),
                ('bhk_choice', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('bed_choice', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19')])),
                ('bathrooms', models.DecimalField(choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (4.0, '4.0')], decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('crested_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aminities', models.ManyToManyField(to='listings.amineties')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
        ),
    ]
