# Generated by Django 5.2.8 on 2025-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wifi', 'Wi-Fi'), ('tv', 'TV'), ('kitchen', 'Kitchen'), ('washer', 'Washer'), ('dryer', 'Dryer'), ('air_conditioning', 'Air Conditioning'), ('heating', 'Heating'), ('dedicated_workspace', 'Dedicated Workspace'), ('parking', 'Free Parking'), ('gym', 'Gym'), ('pool', 'Pool'), ('hot_tub', 'Hot Tub'), ('bbq_grill', 'BBQ Grill'), ('patio', 'Patio or Balcony'), ('garden', 'Garden'), ('smoke_alarm', 'Smoke Alarm'), ('first_aid_kit', 'First Aid Kit'), ('fire_extinguisher', 'Fire Extinguisher'), ('breakfast', 'Breakfast Provided'), ('pets_allowed', 'Pets Allowed'), ('long_term_stays', 'Long-Term Stays Allowed')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Listing Images',
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('hotel', 'Hotel Room'), ('shared_room', 'Shared Room'), ('guest_house', 'Guest House')], max_length=15)),
                ('max_guests', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')])),
                ('bhk_choice', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('bed_choice', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19')])),
                ('bathrooms', models.DecimalField(choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (4.0, '4.0')], decimal_places=1, max_digits=3)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='listings.amenities')),
            ],
            options={
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
