# Generated by Django 5.2.8 on 2026-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_listings_allows_children_listings_allows_infants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenities",
            name="name",
            field=models.CharField(
                choices=[
                    ("wifi", "Wi-Fi"),
                    ("tv", "TV"),
                    ("kitchen", "Kitchen"),
                    ("washer", "Washer"),
                    ("dryer", "Dryer"),
                    ("air_conditioning", "Air Conditioning"),
                    ("heating", "Heating"),
                    ("dedicated_workspace", "Dedicated Workspace"),
                    ("parking", "Free Parking"),
                    ("gym", "Gym"),
                    ("pool", "Pool"),
                    ("hot_tub", "Hot Tub"),
                    ("bbq_grill", "BBQ Grill"),
                    ("patio", "Patio or Balcony"),
                    ("garden", "Garden"),
                    ("smoke_alarm", "Smoke Alarm"),
                    ("first_aid_kit", "First Aid Kit"),
                    ("fire_extinguisher", "Fire Extinguisher"),
                    ("breakfast", "Breakfast Provided"),
                    ("long_term_stays", "Long-Term Stays Allowed"),
                ],
                max_length=100,
            ),
        ),
    ]
