# Generated by Django 5.2.8 on 2026-01-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_amenities_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="pet_fee",
        ),
    ]
