# Generated by Django 5.2.8 on 2026-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listingimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='allows_children',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='allows_pets',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='max_guests',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], db_index=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('hotel', 'Hotel Room'), ('shared_room', 'Shared Room'), ('guest_house', 'Guest House')], db_index=True, max_length=15),
        ),
    ]
