# Generated by Django 5.2.8 on 2026-06-28 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listings_allows_children_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listings',
            name='unique_host_address',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='bedrooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='beds',
            new_name='beds',
        ),
        migrations.AlterField(
            model_name='listings',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
